export const GET_PRODUCTS = 'product/get_products'
export const GET_PRODUCT = 'product/get_product'
export const DECREASE_STOCK = 'product/decrease_stock'
export const INCREASE_STOCK = 'product/increase_stock'
export const RESET_PRODUCT = 'product/RESET_PRODUCT'